### ISSUE TITLE
Failed to load p2 metadata repository from location jar:https://dl.bintray.com/15knots/p2-zip/CMakeEd-1.10.0.zip!/

### ISSUE THREAD

**Issue by kolipakakondal** [15knots/cmakeed#10]
I am using this link in our product update site **jar:https://dl.bintray.com/15knots/p2-zip/CMakeEd-1.10.0.zip!/** but it fails to get the p2 metadata. 

And, this doesn't happen every time but very frequently I could see this error. Does it mean that https://dl.bintray.com/15knots/p2-zip/CMakeEd-1.10.0.zip!/ is unstable?

Here is the log
`org.apache.maven.MavenExecutionException: Failed to resolve target definition /builds/idf/idf-eclipse-plugin/releng/com.espressif.idf.target/com.espressif.idf.target.target: Failed to load p2 metadata repository from location jar:https://dl.bintray.com/15knots/p2-zip/CMakeEd-1.10.0.zip!/
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:100)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:267)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.tycho.core.shared.BuildFailureException: Failed to resolve target definition /builds/idf/idf-eclipse-plugin/releng/com.espressif.idf.target/com.espressif.idf.target.target: Failed to load p2 metadata repository from location jar:https://dl.bintray.com/15knots/p2-zip/CMakeEd-1.10.0.zip!/
	at `

**Comment by 15knots** [comment]
Am Do., 22. Aug. 2019 um 08:53 Uhr schrieb Kondal Kolipaka <
notifications@github.com>:

> I am using this link in our product update site *jar:https://dl.bintray.com/15knots/p2-zip/CMakeEd-1.10.0.zip!/
> <https://dl.bintray.com/15knots/p2-zip/CMakeEd-1.10.0.zip!/>* but it
> fails to get the p2 metadata.
>
> And, this doesn't happen every time but very frequently I could see this
> error. Does it mean that https://dl.bintray.com is unstable?
>

I have no issues here.
Maybe their content-delivery-network has hickups.

**Comment by 15knots** [comment]
Am Do., 22. Aug. 2019 um 08:53 Uhr schrieb Kondal Kolipaka
<notifications@github.com>:
>
> I am using this link in our product update site jar:https://dl.bintray.com/15knots/p2-zip/CMakeEd-1.10.0.zip!/ but it fails to get the p2 metadata.

BTW: current version is 1.12

**Comment by kolipakakondal** [comment]
Thanks @15knots, seems to be bintray is unstable for content delivery

I'll use 1.12 version.

**Comment by 15knots** [comment]
Am Fr., 23. Aug. 2019 um 13:25 Uhr schrieb Kondal Kolipaka <
notifications@github.com>:

> Thanks @15knots <https://github.com/15knots>, seems to be bintray is
> unstable for content delivery
>
You may want to set up a company-internal mirror of external p2-repos and
use the mirror in your target-platform.

**Comment by kolipakakondal** [comment]
Sure, that's the better way. Thanks

**Comment by kolipakakondal** [comment]
BTW, thanks for the good work and I'll be suggesting this plugin for the espressif eclipse users.

**Comment by 15knots** [comment]
You might also suggest cmake4eclipse.

Am Fr., 23. Aug. 2019 um 14:23 Uhr schrieb Kondal Kolipaka <
notifications@github.com>:
